name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  test_and_build:
    name: 'Test and build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: npm ci
      - run: npm run source:check
      - run: npm test
      - run: npm run build

  upload_code_coverage:
    name: 'Upload code coverage'
    needs: ['test_and_build']
    runs-on: ubuntu-latest

    steps:
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
