---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: npm ci
      - run: npm run source:check
      - run: npm test
      - run: npm run build

      - name: Upload code coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
